// <auto-generated />
using System;
using IBI_SmartHome_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IBI_SmartHome_System.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260323184153_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.ActivityLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("HouseId");

                    b.ToTable("ActivityLogEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeviceId = 801,
                            Event = "Front Door Locked",
                            HouseId = 1,
                            Timestamp = new DateTime(2026, 3, 23, 18, 36, 53, 431, DateTimeKind.Utc).AddTicks(267),
                            Type = "info"
                        },
                        new
                        {
                            Id = 2,
                            Event = "Motion Detected at Front Porch",
                            HouseId = 1,
                            Timestamp = new DateTime(2026, 3, 23, 18, 26, 53, 431, DateTimeKind.Utc).AddTicks(274),
                            Type = "warning"
                        },
                        new
                        {
                            Id = 3,
                            DeviceId = 802,
                            Event = "Back Door Unlocked",
                            HouseId = 1,
                            Timestamp = new DateTime(2026, 3, 23, 18, 11, 53, 431, DateTimeKind.Utc).AddTicks(275),
                            Type = "info"
                        },
                        new
                        {
                            Id = 4,
                            Event = "Admin Logged In",
                            HouseId = 1,
                            Timestamp = new DateTime(2026, 3, 23, 17, 41, 53, 431, DateTimeKind.Utc).AddTicks(276),
                            Type = "success"
                        });
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<bool>("DarkModeEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ReceiveNotifications")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "64882ab4-569f-4f46-aa39-ce6c2acee221",
                            DarkModeEnabled = false,
                            Email = "admin@smarthome.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@SMARTHOME.COM",
                            NormalizedUserName = "ADMIN@SMARTHOME.COM",
                            PhoneNumberConfirmed = false,
                            ReceiveNotifications = true,
                            SecurityStamp = "0db128b1-bcbf-4097-b24b-53b212a133a9",
                            TwoFactorEnabled = false,
                            UserName = "admin@smarthome.com",
                            UserRole = "Admin"
                        });
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.AutomationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionDeviceId")
                        .HasColumnType("int");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ActionValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double?>("ConditionValue")
                        .HasColumnType("double");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TriggerDeviceId")
                        .HasColumnType("int");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ActionDeviceId");

                    b.HasIndex("TriggerDeviceId");

                    b.ToTable("AutomationRules");
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.Camera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StreamUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.ToTable("Cameras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HouseId = 1,
                            IsLive = true,
                            Name = "Front Porch Camera",
                            StreamUrl = "http://localhost:8080/video"
                        },
                        new
                        {
                            Id = 2,
                            HouseId = 1,
                            IsLive = false,
                            Name = "Backyard Camera",
                            StreamUrl = "https://example.com/stream/backyard"
                        });
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.ClimateSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Temp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.ToTable("ClimateSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Day = "Mon-Fri",
                            HouseId = 1,
                            Mode = "Heat",
                            Temp = "72°",
                            Time = "07:00 AM"
                        },
                        new
                        {
                            Id = 2,
                            Day = "Mon-Fri",
                            HouseId = 1,
                            Mode = "Eco",
                            Temp = "68°",
                            Time = "09:00 AM"
                        },
                        new
                        {
                            Id = 3,
                            Day = "Mon-Fri",
                            HouseId = 1,
                            Mode = "Heat",
                            Temp = "72°",
                            Time = "05:00 PM"
                        },
                        new
                        {
                            Id = 4,
                            Day = "Sat-Sun",
                            HouseId = 1,
                            Mode = "Heat",
                            Temp = "72°",
                            Time = "08:00 AM"
                        },
                        new
                        {
                            Id = 5,
                            Day = "Sat-Sun",
                            HouseId = 1,
                            Mode = "Sleep",
                            Temp = "67°",
                            Time = "11:00 PM"
                        });
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDoor")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsWindow")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MqttTopic")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.HasIndex("RoomId");

                    b.ToTable("Device");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            HouseId = 1,
                            IsDoor = false,
                            IsLocked = false,
                            IsWindow = false,
                            MqttTopic = "telemetry/lamp/livingroom",
                            Name = "Living Room Lamp",
                            RoomId = 11,
                            Type = 1
                        },
                        new
                        {
                            Id = 401,
                            HouseId = 1,
                            IsDoor = false,
                            IsLocked = false,
                            IsWindow = false,
                            MqttTopic = "telemetry/motionsensor/livingroom",
                            Name = "Living Room Motion Sensor",
                            RoomId = 11,
                            Type = 3
                        },
                        new
                        {
                            Id = 701,
                            HouseId = 1,
                            IsDoor = false,
                            IsLocked = false,
                            IsWindow = false,
                            MqttTopic = "telemetry/tempsensor/livingroom",
                            Name = "Living Room Temperature Sensor",
                            RoomId = 11,
                            Type = 2
                        },
                        new
                        {
                            Id = 801,
                            HouseId = 1,
                            IsDoor = true,
                            IsLocked = true,
                            IsWindow = false,
                            MqttTopic = "security/door/front",
                            Name = "Front Door",
                            RoomId = 11,
                            Type = 4
                        },
                        new
                        {
                            Id = 802,
                            HouseId = 1,
                            IsDoor = true,
                            IsLocked = false,
                            IsWindow = false,
                            MqttTopic = "security/door/back",
                            Name = "Back Door",
                            RoomId = 11,
                            Type = 4
                        },
                        new
                        {
                            Id = 803,
                            HouseId = 1,
                            IsDoor = false,
                            IsLocked = true,
                            IsWindow = true,
                            MqttTopic = "security/window/guest",
                            Name = "Guest Window",
                            RoomId = 12,
                            Type = 4
                        });
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Houses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Smart Home Lane, Sofia",
                            Latitude = 42.700000000000003,
                            Longitude = 23.32,
                            Name = "Admin's Home",
                            UserId = "8e445865-a24d-4543-a6c6-9443d048cdb9"
                        });
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.Lamp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Brightness")
                        .HasColumnType("int");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOn")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("Lamps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brightness = 75,
                            Color = 1,
                            DeviceId = 101,
                            IsOn = false
                        });
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.MotionSensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BatteryLevel")
                        .HasColumnType("double");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMotionDetected")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastMotionDetected")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SensitivityLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("MotionSensor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatteryLevel = 100.0,
                            DeviceId = 401,
                            IsMotionDetected = false,
                            SensitivityLevel = 7
                        });
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.MqttMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("MqttMessages");
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            Floor = "First",
                            HouseId = 1,
                            Name = "Living Room/Kitchen"
                        },
                        new
                        {
                            Id = 12,
                            Floor = "First",
                            HouseId = 1,
                            Name = "Guest Bedroom"
                        },
                        new
                        {
                            Id = 13,
                            Floor = "First",
                            HouseId = 1,
                            Name = "Utility"
                        },
                        new
                        {
                            Id = 14,
                            Floor = "First",
                            HouseId = 1,
                            Name = "Bathroom"
                        },
                        new
                        {
                            Id = 15,
                            Floor = "First",
                            HouseId = 1,
                            Name = "Hallway"
                        },
                        new
                        {
                            Id = 16,
                            Floor = "First",
                            HouseId = 1,
                            Name = "Mudroom"
                        },
                        new
                        {
                            Id = 21,
                            Floor = "Second",
                            HouseId = 1,
                            Name = "Master Bedroom"
                        },
                        new
                        {
                            Id = 22,
                            Floor = "Second",
                            HouseId = 1,
                            Name = "Master Bathroom"
                        },
                        new
                        {
                            Id = 23,
                            Floor = "Second",
                            HouseId = 1,
                            Name = "Ivan Bedroom"
                        },
                        new
                        {
                            Id = 24,
                            Floor = "Second",
                            HouseId = 1,
                            Name = "Ivan Bathroom"
                        },
                        new
                        {
                            Id = 25,
                            Floor = "Second",
                            HouseId = 1,
                            Name = "Neli Bedroom"
                        },
                        new
                        {
                            Id = 26,
                            Floor = "Second",
                            HouseId = 1,
                            Name = "Neli Bathroom"
                        },
                        new
                        {
                            Id = 27,
                            Floor = "Second",
                            HouseId = 1,
                            Name = "Hallway"
                        },
                        new
                        {
                            Id = 28,
                            Floor = "Second",
                            HouseId = 1,
                            Name = "Office"
                        },
                        new
                        {
                            Id = 99,
                            Floor = "Ground",
                            HouseId = 1,
                            Name = "Outdoor"
                        });
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.Scene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.ToTable("Scenes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HouseId = 1,
                            Name = "Arrive Home"
                        },
                        new
                        {
                            Id = 2,
                            HouseId = 1,
                            Name = "Leave Home"
                        },
                        new
                        {
                            Id = 3,
                            HouseId = 1,
                            Name = "Good Morning"
                        },
                        new
                        {
                            Id = 4,
                            HouseId = 1,
                            Name = "Good Night"
                        });
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.SceneAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SceneId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("SceneId");

                    b.ToTable("SceneActions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeviceId = 101,
                            Property = "Power",
                            SceneId = 1,
                            Value = "true"
                        },
                        new
                        {
                            Id = 2,
                            DeviceId = 101,
                            Property = "Power",
                            SceneId = 2,
                            Value = "false"
                        },
                        new
                        {
                            Id = 3,
                            DeviceId = 101,
                            Property = "Power",
                            SceneId = 3,
                            Value = "true"
                        },
                        new
                        {
                            Id = 4,
                            DeviceId = 101,
                            Property = "Brightness",
                            SceneId = 3,
                            Value = "100"
                        },
                        new
                        {
                            Id = 5,
                            DeviceId = 101,
                            Property = "Color",
                            SceneId = 3,
                            Value = "White"
                        },
                        new
                        {
                            Id = 6,
                            DeviceId = 101,
                            Property = "Power",
                            SceneId = 4,
                            Value = "false"
                        },
                        new
                        {
                            Id = 7,
                            DeviceId = 701,
                            Property = "TemperatureValue",
                            SceneId = 4,
                            Value = "18"
                        });
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.Temperature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("Humidity")
                        .HasColumnType("int");

                    b.Property<int>("TargetTemperature")
                        .HasColumnType("int");

                    b.Property<double>("TemperatureValue")
                        .HasColumnType("double");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("Temperature");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeviceId = 701,
                            Humidity = 45,
                            TargetTemperature = 0,
                            TemperatureValue = 22.5,
                            Timestamp = new DateTime(2026, 3, 23, 13, 41, 53, 430, DateTimeKind.Utc).AddTicks(9915)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.ActivityLogEntry", b =>
                {
                    b.HasOne("IBI_SmartHome_System.Data.Entity.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId");

                    b.HasOne("IBI_SmartHome_System.Data.Entity.House", "House")
                        .WithMany("ActivityLogEntries")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("House");
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.AutomationRule", b =>
                {
                    b.HasOne("IBI_SmartHome_System.Data.Entity.Device", "ActionDevice")
                        .WithMany()
                        .HasForeignKey("ActionDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IBI_SmartHome_System.Data.Entity.Device", "TriggerDevice")
                        .WithMany()
                        .HasForeignKey("TriggerDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActionDevice");

                    b.Navigation("TriggerDevice");
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.Camera", b =>
                {
                    b.HasOne("IBI_SmartHome_System.Data.Entity.House", "House")
                        .WithMany("Cameras")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.ClimateSchedule", b =>
                {
                    b.HasOne("IBI_SmartHome_System.Data.Entity.House", "House")
                        .WithMany("ClimateSchedules")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.Device", b =>
                {
                    b.HasOne("IBI_SmartHome_System.Data.Entity.House", "House")
                        .WithMany()
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IBI_SmartHome_System.Data.Entity.Room", "Room")
                        .WithMany("Devices")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("House");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.House", b =>
                {
                    b.HasOne("IBI_SmartHome_System.Data.Entity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.Lamp", b =>
                {
                    b.HasOne("IBI_SmartHome_System.Data.Entity.Device", "Device")
                        .WithOne("Lamp")
                        .HasForeignKey("IBI_SmartHome_System.Data.Entity.Lamp", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.MotionSensor", b =>
                {
                    b.HasOne("IBI_SmartHome_System.Data.Entity.Device", "Device")
                        .WithOne("MotionSensor")
                        .HasForeignKey("IBI_SmartHome_System.Data.Entity.MotionSensor", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.MqttMessage", b =>
                {
                    b.HasOne("IBI_SmartHome_System.Data.Entity.Device", "Device")
                        .WithMany("MqttMessages")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.Room", b =>
                {
                    b.HasOne("IBI_SmartHome_System.Data.Entity.House", "House")
                        .WithMany("Rooms")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.Scene", b =>
                {
                    b.HasOne("IBI_SmartHome_System.Data.Entity.House", "House")
                        .WithMany("Scenes")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.SceneAction", b =>
                {
                    b.HasOne("IBI_SmartHome_System.Data.Entity.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IBI_SmartHome_System.Data.Entity.Scene", "Scene")
                        .WithMany("SceneActions")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.Temperature", b =>
                {
                    b.HasOne("IBI_SmartHome_System.Data.Entity.Device", "Device")
                        .WithOne("Temperature")
                        .HasForeignKey("IBI_SmartHome_System.Data.Entity.Temperature", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("IBI_SmartHome_System.Data.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("IBI_SmartHome_System.Data.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IBI_SmartHome_System.Data.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("IBI_SmartHome_System.Data.Entity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.Device", b =>
                {
                    b.Navigation("Lamp");

                    b.Navigation("MotionSensor");

                    b.Navigation("MqttMessages");

                    b.Navigation("Temperature");
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.House", b =>
                {
                    b.Navigation("ActivityLogEntries");

                    b.Navigation("Cameras");

                    b.Navigation("ClimateSchedules");

                    b.Navigation("Rooms");

                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.Room", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("IBI_SmartHome_System.Data.Entity.Scene", b =>
                {
                    b.Navigation("SceneActions");
                });
#pragma warning restore 612, 618
        }
    }
}
