<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	<Nullable>disable</Nullable>
	<WarningsAsErrors></WarningsAsErrors>
	<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-IBI_SmartHome_System-249fd0b2-ba9f-4769-8cde-f143d82de729</UserSecretsId>
    <RootNamespace>IBI_SmartHome_System</RootNamespace>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.22" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.22" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.22" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.22" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IBI SmartHome System.Data\IBI SmartHome System.Data.csproj" />
    <ProjectReference Include="..\IBI SmartHome System.Service\IBI SmartHome System.Service.csproj" />
  </ItemGroup>

</Project>
