<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>IBI_SmartHome_System.Service</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.22" />
    <PackageReference Include="MQTTnet" Version="4.3.7.1207" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IBI SmartHome System.Data\IBI SmartHome System.Data.csproj" />
  </ItemGroup>

</Project>
